version: "3.8"
services:
  webapi:
    hostname: webapi
    ports:
      - 8080:8080
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: go-reg-webapi
    environment:
      - DB_CONN=redis://default:password@redis:6379
      - SECRET=KNEDLIK
    depends_on:
      - redis
  redis:
    hostname: redis
    image: redis
    container_name: go-reg-redis
    ports:
      - 6379
    volumes:
      - ./redis-data:/data
    environment:
      - REDIS_PASSWORD="password"
      - REDIS_PORT=6379
      - REDIS_DATABASES=1

